version: "3.9"

services:
  svelte-dev:
    image: marcpartensky/svelte-template
    restart: unless-stopped
    build: .
    ports:
      - "5000:5000"

  svelte-prod:
    image: marcpartensky/svelte-template
    restart: unless-stopped
    build: .
    networks:
      - caddy
    labels:
      - "caddy=svelte.marcpartensky.com"
      - "caddy.reverse_proxy={{upstreams http 5000}}"

networks:
  caddy:
    external: true
